# Site settings
title: C.S. Rhymes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  C.S. Rhymes author of How NOT to make a website and How NOT to use a smartphone
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://www.csrhymes.com # the base hostname & protocol for your site
twitter_username: chrisrhymes
github_username:  chrisrhymes

# Build settings
markdown: kramdown

#Syntax Highlighter
#highlighter: rouge

gems:
  - jekyll-sitemap
